# Generated by Django 4.2.15 on 2024-09-14 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooltokenprice',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время получения цены'),
        ),
    ]
