# Generated by Django 4.2.15 on 2024-09-14 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pairs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название подборки')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('pools', models.ManyToManyField(related_name='pool_lists', to='pairs.pools', verbose_name='Пулы')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_lists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подборка пулов',
                'verbose_name_plural': 'Подборки пулов',
                'db_table': 'pool_list',
            },
        ),
        migrations.AddConstraint(
            model_name='usercollections',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_list_name'),
        ),
    ]
