version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - ./postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    env_file:
      - ./postgres.env
    environment:
      START_IN_DOCKER: True
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
